(() => {
  'use strict';
  const API = '/api/learning';
  const lessons = {
    'cyber-basics': {
      ar: {
        name: 'أساسيات الأمن السيبراني', desc: 'مسار تأسيسي لفهم المخاطر الرقمية وحماية الحسابات والبيانات.', level: 'سهل · مبتدئ', lessons: [
          { title: 'مقدمة الأمن السيبراني', body: 'الأمن السيبراني هو مجموعة الممارسات والتقنيات التي تحمي الأجهزة والشبكات والبيانات من الوصول غير المصرح به أو التغيير أو التعطيل. يبدأ الأمن الجيد بفهم ما نملكه وما نريد حمايته ومن المخاطر المحتملة.', points: ['السرية: لا يطلع على البيانات إلا المصرح لهم.', 'السلامة: تبقى البيانات صحيحة وغير معدلة دون إذن.', 'التوافر: تبقى الخدمات متاحة عند الحاجة.'], example: 'مثال عملي: قبل تثبيت تطبيق جديد، تحقق من مصدره وصلاحياته واقرأ تقييماته.' },
          { title: 'إدارة الحسابات وكلمات المرور', body: 'الحسابات هي بوابة الوصول إلى بياناتك. استخدم كلمة مرور طويلة وفريدة لكل خدمة، وفعّل المصادقة متعددة العوامل، ولا تشارك رموز الدخول مع أي شخص.', points: ['استخدم مدير كلمات مرور موثوقًا.', 'فعّل MFA للحسابات المهمة.', 'راجع جلسات الدخول والأجهزة المرتبطة دوريًا.'], example: 'تدريب: أنشئ عبارة مرور من أربع كلمات غير مترابطة وأضف رمزًا، بدل كلمة قصيرة قابلة للتخمين.' },
          { title: 'الهندسة الاجتماعية', body: 'الهندسة الاجتماعية تستغل ثقة الإنسان أو استعجاله بدل استغلال ثغرة تقنية. قد تصل الرسالة منتحلة اسم جهة موثوقة وتطلب رابطًا أو ملفًا أو رمز تحقق.', points: ['توقف قبل الرد على الطلبات العاجلة.', 'تحقق من العنوان والقناة الرسمية.', 'لا تشارك رمز التحقق أو بيانات الدخول.'], example: 'إذا طلبت رسالة تحويلًا عاجلًا، اتصل بالجهة عبر رقمها الرسمي بدل الرد على الرسالة.' },
          { title: 'التصفح والبريد الآمن', body: 'افحص عنوان الموقع قبل إدخال البيانات، وانتبه للتشابه بين الحروف وأسماء النطاقات. وجود HTTPS مفيد لكنه لا يثبت وحده أن الموقع موثوق.', points: ['اكتب العنوان يدويًا للمواقع الحساسة.', 'لا تفتح مرفقات غير متوقعة.', 'حدّث المتصفح ونظام التشغيل.'], example: 'مرّر المؤشر على الرابط قبل الضغط وتأكد أن النطاق هو النطاق الرسمي وليس نطاقًا مشابهًا.' },
          { title: 'المراجعة النهائية', body: 'اجمع ما تعلمته في قائمة سلوك يومية: حدّث أجهزتك، استخدم كلمات مرور فريدة، فعّل MFA، تحقق من الروابط، وخذ نسخًا احتياطية مشفرة.', points: ['المخاطر تتغير باستمرار.', 'التدريب والوعي جزء من الحماية.', 'أبلغ عن الحوادث بسرعة.'], example: 'أنشئ قائمة مراجعة شهرية للحسابات والأجهزة والنسخ الاحتياطية.' }
        ]
      },
      en: { name: 'Cybersecurity Basics', desc: 'A foundation path for understanding digital risks and protecting accounts and data.', level: 'Easy · Beginner', lessons: [
        { title: 'Cybersecurity introduction', body: 'Cybersecurity combines practices and technologies that protect devices, networks, and data from unauthorized access, alteration, or disruption. Good security starts by identifying what we own and what we need to protect.', points: ['Confidentiality: only authorized people access data.', 'Integrity: data remains accurate and trustworthy.', 'Availability: services remain accessible when needed.'], example: 'Practical example: before installing an app, verify its source, permissions, and reputation.' },
        { title: 'Accounts and passwords', body: 'Accounts are gateways to your data. Use a long, unique password for every service, enable multi-factor authentication, and never share login codes.', points: ['Use a trusted password manager.', 'Enable MFA on important accounts.', 'Review active sessions and devices regularly.'], example: 'Practice: create a passphrase from four unrelated words and add a symbol.' },
        { title: 'Social engineering', body: 'Social engineering exploits trust and urgency instead of a technical vulnerability. A message may impersonate a trusted organization and request a link, file, or code.', points: ['Pause before responding to urgent requests.', 'Verify through an official channel.', 'Never share verification codes.'], example: 'If a message requests an urgent transfer, call the organization using its official number.' },
        { title: 'Safe browsing and email', body: 'Check a website address before entering data. Watch for look-alike domains. HTTPS helps protect traffic but does not prove that a site is trustworthy.', points: ['Type sensitive addresses manually.', 'Do not open unexpected attachments.', 'Keep browsers and operating systems updated.'], example: 'Hover over a link and verify the domain before clicking.' },
        { title: 'Final review', body: 'Turn your learning into daily habits: update devices, use unique passwords, enable MFA, verify links, and keep encrypted backups.', points: ['Risks change over time.', 'Awareness is part of security.', 'Report incidents quickly.'], example: 'Create a monthly checklist for accounts, devices, and backups.' }
      ] }
    },
    'network-defense': {
      ar: { name: 'الدفاع عن الشبكات', desc: 'مسار متوسط لفهم مراقبة الشبكات وتحليل السجلات والاستجابة للحوادث.', level: 'متوسط الصعوبة', lessons: ['مبادئ الشبكات','الجدران النارية','قراءة السجلات','كشف التهديدات','الاستجابة للحوادث'].map((title, i) => ({ title, body: ['الشبكة مجموعة أجهزة تتبادل البيانات عبر بروتوكولات وقواعد محددة. فهم العناوين والمنافذ والتدفق يساعد المدافع على اكتشاف السلوك غير المعتاد.', 'الجدار الناري يطبق قواعد تسمح أو تمنع حركة المرور. يجب أن تكون القواعد محددة ومراجعة، وأن يُمنع الوصول غير الضروري افتراضيًا.', 'السجلات تسجل الأحداث المهمة مثل محاولات الدخول والاتصالات والأخطاء. قراءة التوقيت والمصدر والوجهة تكشف الأنماط المتكررة.', 'الكشف يبدأ بوضع خط أساس للسلوك الطبيعي ثم مقارنة الأحداث به. الارتفاع المفاجئ في المحاولات أو الاتصال بوجهات غير مألوفة يستحق التحقيق.', 'الاستجابة المنظمة تقلل الضرر. اعزل النظام المتأثر، احفظ الأدلة، أبلغ الفريق، ثم عالج السبب واختبر العودة الآمنة.'][i], points: ['حدد السلوك الطبيعي أولًا.', 'قلل الصلاحيات والمنافذ المكشوفة.', 'وثّق كل قرار أثناء التحقيق.'], example: 'تطبيق عملي: راقب ثلاث محاولات دخول فاشلة متتالية من مصدر واحد وسجّل وقتها ومصدرها وإجراءك.' })) },
      en: { name: 'Network Defense', desc: 'An intermediate path covering network monitoring, logs, and incident response.', level: 'Intermediate', lessons: ['Network principles','Firewalls','Log analysis','Threat detection','Incident response'].map((title, i) => ({ title, body: ['A network connects devices through defined protocols and rules. Understanding addresses, ports, and flows helps defenders spot unusual behavior.', 'A firewall applies rules that allow or deny traffic. Rules should be specific, reviewed, and deny unnecessary access by default.', 'Logs record events such as login attempts, connections, and errors. Time, source, and destination reveal recurring patterns.', 'Detection starts with a baseline of normal behavior. Sudden spikes or unusual destinations deserve investigation.', 'A structured response limits damage: isolate the system, preserve evidence, notify the team, remediate the cause, and test recovery.'][i], points: ['Define normal behavior first.', 'Reduce exposed ports and privileges.', 'Document every investigation decision.'], example: 'Practice: record three failed logins from one source with time, origin, and response.' })) }
    },
    'ethical-hacking': {
      ar: { name: 'الاختبار الاختراقي الأخلاقي', desc: 'مسار متقدم للاختبار المصرح به واكتشاف الثغرات وكتابة التقارير.', level: 'صعب · متقدم', lessons: ['النطاق والتصريح','جمع المعلومات','فحص الثغرات','الاستغلال الآمن','كتابة التقرير'].map((title, i) => ({ title, body: ['يبدأ الاختبار الأخلاقي بتصريح مكتوب ونطاق واضح وقواعد للتعامل مع البيانات والأنظمة. لا تختبر أي أصل خارج النطاق.', 'جمع المعلومات مرحلة منظمة لفهم الأصول المعلنة دون إحداث تأثير. استخدم مصادر مصرحًا بها ووثّق مستوى الثقة.', 'فحص الثغرات يحدد مؤشرات الضعف، لكنه ليس إثباتًا نهائيًا. راجع النتائج وقلل الإيجابيات الكاذبة قبل التوصية.', 'الاستغلال يجب أن يكون محدودًا وآمنًا ومصرحًا به. تجنب تعطيل الخدمة أو الوصول إلى بيانات حقيقية غير لازمة.', 'التقرير الجيد يشرح الأثر والدليل وخطوات الإصلاح والأولوية، ويمنح الفريق طريقة واضحة للتحقق من المعالجة.'][i], points: ['لا اختبار بلا تصريح.', 'احفظ الأدلة دون بيانات زائدة.', 'اكتب توصيات قابلة للتنفيذ.'], example: 'ممارسة آمنة: استخدم مختبرًا محليًا أو بيئة تدريبية بدل اختبار أنظمة عامة.' })) },
      en: { name: 'Ethical Hacking', desc: 'An advanced path for authorized testing, vulnerability discovery, and reporting.', level: 'Hard · Advanced', lessons: ['Scope and authorization','Reconnaissance','Vulnerability scanning','Safe exploitation','Report writing'].map((title, i) => ({ title, body: ['Ethical testing begins with written authorization, a clear scope, and rules for handling systems and data. Never test outside scope.', 'Reconnaissance builds an understanding of public assets without impact. Use authorized sources and document confidence.', 'Scanning identifies indicators of weakness but is not final proof. Validate findings and reduce false positives.', 'Exploitation must be limited, safe, and authorized. Avoid disrupting services or accessing unnecessary real data.', 'A good report explains impact, evidence, remediation, and priority, with a clear retest path.'][i], points: ['Never test without authorization.', 'Preserve only necessary evidence.', 'Write actionable remediation advice.'], example: 'Safe practice: use a local lab or training environment instead of public systems.' })) }
    }
  };
  const quiz = { ar: ['ما الخطوة الصحيحة قبل تطبيق المعرفة على نظام حقيقي؟', ['الحصول على تصريح وتحديد النطاق', 'تجربة أي أداة دون قيود', 'مشاركة بيانات النظام'], 0], en: ['What should happen before applying knowledge to a real system?', ['Obtain authorization and define scope', 'Run any tool without limits', 'Share system data'], 0] };
  const buildTrack = (config) => ({ ar: { name: config.arName, desc: config.arDesc, level: config.arLevel, lessons: config.arLessons.map((title, index) => ({ title, body: config.arBodies[index], points: config.arPoints[index], example: config.arExamples[index] })) }, en: { name: config.enName, desc: config.enDesc, level: config.enLevel, lessons: config.enLessons.map((title, index) => ({ title, body: config.enBodies[index], points: config.enPoints[index], example: config.enExamples[index] })) } });
  Object.assign(data, {
    'digital-literacy': buildTrack({ arName: 'الوعي الرقمي الآمن', enName: 'Digital Safety Awareness', arDesc: 'الخصوصية والهوية الرقمية وإدارة المخاطر اليومية.', enDesc: 'Privacy, digital identity, and everyday risk management.', arLevel: 'سهل · مبتدئ', enLevel: 'Easy · Beginner', arLessons: ['الهوية الرقمية','الخصوصية على الإنترنت','الأجهزة والتحديثات','التعامل مع المحتوى المضلل','خطة السلوك الآمن'], enLessons: ['Digital identity','Online privacy','Devices and updates','Misinformation','Safe behavior plan'], arBodies: ['الهوية الرقمية هي الصورة التي تتكون عنك من حساباتك ونشاطك ومشاركاتك. إدارة هذه الصورة تبدأ بتقليل المعلومات غير الضرورية ومراجعة إعدادات الحسابات.', 'الخصوصية لا تعني الاختفاء؛ بل تعني اختيار ما تشاركه ومن يستطيع الوصول إليه. افصل بين الحسابات الشخصية والعامة واستخدم إعدادات الخصوصية.', 'التحديثات تسد ثغرات معروفة وتحسن الاستقرار. استخدم مصادر رسمية، وقفل الشاشة، ونسخة احتياطية عند الحاجة.', 'المحتوى المضلل قد يستخدم عنوانًا مثيرًا أو صورة خارج سياقها. تحقق من المصدر والتاريخ وابحث عن تأكيد مستقل قبل المشاركة.', 'السلوك الآمن عادة متكررة: توقف، تحقق، قلل البيانات، وحدّث أجهزتك، وأبلغ عن السلوك الضار.'], enBodies: ['Digital identity is the picture created by your accounts, activity, and posts. Manage it by reducing unnecessary information and reviewing account settings.', 'Privacy is about choosing what to share and who can access it. Separate personal and public accounts and review privacy controls.', 'Updates fix known weaknesses and improve stability. Use official sources, screen locks, and backups when appropriate.', 'Misinformation may use emotional headlines or out-of-context images. Check the source, date, and independent confirmation.', 'Safe behavior is a repeatable habit: pause, verify, minimize data, update devices, and report abuse.'], arPoints: [['راجع ما يظهر عنك في الحسابات.','قلل البيانات العامة.'],['افهم إعدادات المشاركة.','استخدم المصادقة متعددة العوامل.'],['فعّل التحديث التلقائي.','استخدم قفلًا قويًا.'],['افحص المصدر والتاريخ.','لا تنشر قبل التحقق.'],['توقف قبل الضغط.','أبلغ عن المخاطر.']], enPoints: [['Review your public profile.','Minimize public data.'],['Understand sharing controls.','Use MFA.'],['Enable automatic updates.','Use a strong lock.'],['Check source and date.','Verify before sharing.'],['Pause before clicking.','Report risks.']], arExamples: ['ابحث عن اسمك في محركات البحث وسجل ما يحتاج إلى إخفاء.','راجع خصوصية تطبيق اجتماعي واحد اليوم.','تحقق من تحديثات الهاتف وخذ نسخة احتياطية.','قارن خبرًا متداولًا مع مصدر رسمي.','اكتب قائمة تحقق قبل مشاركة أي رابط.'], enExamples: ['Search your name and note what should be hidden.','Review privacy settings for one social app today.','Check phone updates and create a backup.','Compare a viral claim with an official source.','Write a checklist before sharing a link.'] }),
    'digital-forensics': buildTrack({ arName: 'الأدلة الجنائية الرقمية', enName: 'Digital Forensics Fundamentals', arDesc: 'مبادئ جمع الأدلة الرقمية والحفاظ على سلامتها وتحليلها.', enDesc: 'Collecting, preserving, and analyzing digital evidence.', arLevel: 'متوسط الصعوبة', enLevel: 'Intermediate', arLessons: ['مبادئ الدليل الرقمي','سلسلة الحيازة','جمع الأدلة بأمان','تحليل الآثار الزمنية','كتابة التقرير الجنائي'], enLessons: ['Digital evidence principles','Chain of custody','Safe evidence collection','Timeline analysis','Forensic reporting'], arBodies: ['الدليل الرقمي معلومة يمكن أن تساعد في فهم حادثة، مثل سجل أو ملف أو أثر اتصال. يجب تقييم مصدره وسلامته وسياقه.', 'سلسلة الحيازة تسجل من تعامل مع الدليل ومتى وكيف وأين تم حفظه. التوثيق يمنع الشك في سلامة الدليل.', 'اجمع الحد الأدنى اللازم دون تعديل الأصل، واستخدم نسخة عمل موثقة، واحفظ القيم التجزيئية عند الإمكان.', 'الخط الزمني يربط الأحداث بالوقت ويساعد على ترتيب ما حدث. راعِ اختلاف المناطق الزمنية ومصادر الوقت.', 'التقرير الجيد يفرق بين الوقائع والاستنتاجات ويذكر المنهج والقيود والتوصيات بوضوح.'], enBodies: ['Digital evidence is information that helps explain an incident, such as a log, file, or connection trace. Assess source, integrity, and context.', 'A chain of custody records who handled evidence, when, how, and where it was stored. Documentation protects integrity.', 'Collect only what is necessary without modifying the original. Use a documented working copy and record hashes when possible.', 'A timeline links events to time and helps reconstruct what happened. Account for time zones and clock sources.', 'A good report separates facts from conclusions and clearly states method, limits, and recommendations.'], arPoints: [['قيّم المصدر.','احفظ السياق.'],['سجل كل عملية تسليم.','استخدم التخزين المقيد.'],['لا تعدل الأصل.','اعمل على نسخة.'],['رتب الأحداث.','تحقق من مصادر الوقت.'],['اكتب الوقائع أولًا.','اذكر القيود.']], enPoints: [['Assess the source.','Preserve context.'],['Record every transfer.','Restrict storage.'],['Do not alter originals.','Work from a copy.'],['Order events.','Check time sources.'],['State facts first.','Document limitations.']], arExamples: ['صنّف سجلًا إلى مصدر ووقت ومحتوى وثقة.','املأ نموذج تسليم دليل تدريبي.','أنشئ نسخة عمل لملف مختبري.','رتب خمسة أحداث من سجل مختبري.','اكتب ملخصًا محايدًا لحادثة تدريبية.'], enExamples: ['Classify a log by source, time, content, and confidence.','Complete a practice evidence transfer form.','Create a working copy of a lab file.','Order five events from a lab log.','Write a neutral summary of a practice incident.'] }),
    'secure-coding': buildTrack({ arName: 'البرمجة الآمنة وتطبيقات الويب', enName: 'Secure Coding and Web Applications', arDesc: 'بناء تطبيقات ويب أكثر أمانًا عبر التحقق والحماية والاختبار.', enDesc: 'Build safer web applications through validation, protection, and testing.', arLevel: 'متوسط الصعوبة', enLevel: 'Intermediate', arLessons: ['نمذجة التهديدات','التحقق من المدخلات','الجلسات والصلاحيات','حماية الأسرار','اختبار التطبيق الآمن'], enLessons: ['Threat modeling','Input validation','Sessions and authorization','Secret protection','Secure testing'], arBodies: ['نمذجة التهديدات تحول المخاطر إلى سيناريوهات قابلة للنقاش. حدد الأصول والجهات المهاجمة ونقاط الدخول ثم رتب المخاطر.', 'تحقق من المدخلات في الخادم، استخدم قواعد نوع وطول واضحة، واهرب المخرجات في سياقها لتقليل مخاطر الحقن.', 'الجلسة تمثل هوية المستخدم. استخدم كوكيز آمنة، تحقق من الصلاحيات في الخادم، ولا تعتمد على إخفاء زر في الواجهة.', 'لا تضع المفاتيح في الواجهة أو المستودع. استخدم متغيرات بيئة وإدارة أسرار مناسبة ودوّر المفاتيح المكشوفة.', 'اختبر المسارات الحساسة، حالات الخطأ، والصلاحيات بحسابات مختلفة قبل النشر.'], enBodies: ['Threat modeling turns risks into discussable scenarios. Identify assets, attackers, entry points, and priorities.', 'Validate inputs on the server with clear type and length rules, and escape output in context to reduce injection risk.', 'A session represents identity. Use secure cookies, enforce authorization on the server, and never rely on hiding UI controls.', 'Keep keys out of the frontend and repository. Use environment variables and rotate exposed secrets.', 'Test sensitive routes, error cases, and permissions with different accounts before release.'], arPoints: [['حدد الأصول.','رتب المخاطر.'],['تحقق في الخادم.','اهرب المخرجات.'],['افرض الصلاحيات خادميًا.','استخدم كوكيز آمنة.'],['احفظ الأسرار خارج الكود.','دوّر المفاتيح.'],['اختبر الرفض قبل القبول.','وثق النتائج.']], enPoints: [['Identify assets.','Prioritize risks.'],['Validate server-side.','Escape output.'],['Enforce server authorization.','Use secure cookies.'],['Keep secrets out of code.','Rotate keys.'],['Test denial before acceptance.','Document results.']], arExamples: ['ارسم تدفق تسجيل الدخول وحدد نقطة ثقة.','أرسل قيمة طويلة غير متوقعة إلى نموذج مختبري.','اختبر حسابًا عاديًا على مسار إداري في بيئة تدريب.','ابحث عن مفتاح داخل المستودع التدريبي وأزله.','اكتب حالات اختبار لمسار إعادة كلمة المرور.'], enExamples: ['Draw a login flow and mark trust boundaries.','Submit an unexpected long value to a lab form.','Test a normal account against an admin route in a lab.','Find and remove a training key from a repository.','Write test cases for password reset.'] }),
    'cloud-security': buildTrack({ arName: 'أمن الحوسبة السحابية', enName: 'Cloud Security Essentials', arDesc: 'الهوية السحابية وحماية الموارد ومراقبة الخدمات الموزعة.', enDesc: 'Cloud identity, resource protection, and distributed service monitoring.', arLevel: 'صعب · متقدم', enLevel: 'Hard · Advanced', arLessons: ['نموذج المسؤولية المشتركة','الهوية والصلاحيات السحابية','حماية التخزين والشبكات','المراقبة السحابية','خطة الاستجابة السحابية'], enLessons: ['Shared responsibility','Cloud identity and access','Storage and network protection','Cloud monitoring','Cloud response planning'], arBodies: ['المسؤولية المشتركة توضح ما تحميه مزود الخدمة وما يبقى على عاتق العميل. فهم الحدود يمنع الافتراضات الخطرة.', 'الهوية هي المحيط الجديد. امنح أقل صلاحية، استخدم أدوارًا منفصلة، وراقب الحسابات عالية الامتياز.', 'تحقق من إعدادات التخزين والشبكات، وامنع الوصول العام غير الضروري، وفصل البيئات حسب الحاجة.', 'اجمع سجلات الهوية والموارد والشبكة، وحدد تنبيهات قابلة للتنفيذ بدل الضوضاء.', 'خطط لعزل المورد أو الحساب، واحفظ السجلات، ونسق مع الفريق، ثم اختبر التعافي.'], enBodies: ['Shared responsibility defines what the provider secures and what remains the customer’s duty. Understanding boundaries prevents risky assumptions.', 'Identity is the new perimeter. Grant least privilege, separate roles, and monitor privileged accounts.', 'Review storage and network settings, block unnecessary public access, and separate environments where needed.', 'Collect identity, resource, and network logs. Build actionable alerts rather than noise.', 'Plan isolation, preserve logs, coordinate with the team, and test recovery.'], arPoints: [['حدد حدود المسؤولية.','وثق الافتراضات.'],['أقل صلاحية.','افصل الأدوار.'],['امنع الوصول العام.','راجع قواعد الشبكة.'],['اجمع سجلات مهمة.','اضبط تنبيهات عملية.'],['اختبر التعافي.','حدد مسؤوليات الاستجابة.']], enPoints: [['Define boundaries.','Document assumptions.'],['Least privilege.','Separate roles.'],['Block public access.','Review network rules.'],['Collect key logs.','Build actionable alerts.'],['Test recovery.','Assign response roles.']], arExamples: ['اكتب جدولًا يوضح مسؤولية المزود والعميل.','راجع دورًا سحابيًا تدريبيًا واحذف صلاحية غير لازمة.','افحص إعداد وصول عام في مختبر سحابي.','صمم تنبيهًا لمحاولة دخول إدارية فاشلة.','نفذ تمرينًا مكتبيًا لانقطاع خدمة.'], enExamples: ['Create a provider/customer responsibility table.','Review a lab role and remove an unnecessary permission.','Inspect public access in a cloud lab.','Design an alert for a failed admin login.','Run a tabletop outage exercise.'] }),
    'soc-analyst': buildTrack({ arName: 'محلل مركز العمليات الأمنية SOC', enName: 'SOC Analyst Foundations', arDesc: 'الفرز الأمني وتحليل التنبيهات وكتابة تقارير الحوادث.', enDesc: 'Triage, alert analysis, and incident reporting for SOC teams.', arLevel: 'صعب · متقدم', enLevel: 'Hard · Advanced', arLessons: ['دور محلل SOC','فرز التنبيهات','تحليل المؤشرات','التواصل أثناء الحادثة','قياس التحسن'], enLessons: ['SOC analyst role','Alert triage','Indicator analysis','Incident communication','Measuring improvement'], arBodies: ['محلل SOC يربط التنبيهات بالسياق ويحدد الأولوية. الهدف ليس معالجة كل تنبيه بالطريقة نفسها بل تقليل المخاطر بقرارات قابلة للتتبع.', 'الفرز يجمع شدة التنبيه وتأثير الأصل واحتمال الخطر. ابدأ بالبيانات الأكثر فائدة ثم سجل قرارك.', 'المؤشر قد يكون عنوانًا أو نطاقًا أو تجزئة أو سلوكًا. لا تعتمد على مؤشر منفرد دون سياق زمني وبيئي.', 'التواصل الواضح يمنع الارتباك. اذكر ماذا حدث وما الذي نعرفه وما الذي لا نعرفه وما الخطوة التالية.', 'قِس زمن الاكتشاف والاستجابة وجودة التنبيهات ونسبة التكرار، وحول النتائج إلى تحسينات تدريبية وتقنية.'], enBodies: ['A SOC analyst connects alerts to context and prioritizes risk. Not every alert deserves the same response.', 'Triage combines severity, asset impact, and likelihood. Start with useful data and record the decision.', 'An indicator may be an address, domain, hash, or behavior. Never rely on one indicator without time and environment context.', 'Clear communication prevents confusion. State what happened, what is known, unknown, and the next action.', 'Measure detection and response time, alert quality, and recurrence, then turn results into improvements.'], arPoints: [['اربط التنبيه بالسياق.','حدد الأولوية.'],['سجل قرار الفرز.','قلل الضوضاء.'],['اجمع مؤشرات متعددة.','تحقق من السياق.'],['افصل الحقائق عن الافتراضات.','حدد الخطوة التالية.'],['قِس التحسن.','كرر التمرين.']], enPoints: [['Add context.','Prioritize risk.'],['Record triage decisions.','Reduce noise.'],['Correlate indicators.','Check context.'],['Separate facts from assumptions.','Name the next action.'],['Measure improvement.','Repeat exercises.']], arExamples: ['صنف ثلاثة تنبيهات حسب أثر الأصل.','اكتب سبب رفع أولوية تنبيه.','اربط مؤشرًا بسجل زمني في مختبر.','اكتب تحديثًا من ثلاث جمل لفريق الاستجابة.','احسب متوسط زمن الاستجابة لتمرينين.'], enExamples: ['Rank three alerts by asset impact.','Write why an alert was escalated.','Correlate an indicator with a lab timeline.','Write a three-sentence incident update.','Calculate response time across two exercises.'] })
  });
  const slug = new URLSearchParams(location.search).get('course') || 'cyber-basics';
  const course = data[slug] || data['cyber-basics']; let lang = localStorage.getItem('club-lang') === 'en' ? 'en' : 'ar'; let saved = { percent: 0, lastSection: 0, quizScores: {} }; let current = 0;
  const $ = (id) => document.getElementById(id); const msg = (text) => { $('course-message').textContent = text; };
  async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json' }, ...options }); const result = await response.json().catch(() => ({})); if (!response.ok) throw Error(result.error || 'تعذر الاتصال بالخادم'); return result; }
  function renderShell() { const meta = course[lang]; document.documentElement.lang = lang; document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'; $('course-title').textContent = meta.name; $('course-description').textContent = meta.desc; $('course-level').textContent = meta.level; $('course-progress').textContent = `${saved.percent || 0}%`; $('course-progress-bar').style.width = `${saved.percent || 0}%`; document.querySelectorAll('[data-course-lang]').forEach(button => button.classList.toggle('active', button.dataset.courseLang === lang)); renderLessonList(meta.lessons); }
  function renderLessonList(items) { const list = $('lessons'); list.innerHTML = items.map((lesson, index) => `<button class="lesson-nav ${index === current ? 'active' : ''} ${saved.quizScores?.[index] ? 'passed' : ''}" data-lesson-index="${index}"><span class="lesson-number">${index + 1}</span><span><strong>${lesson.title}</strong><small>${saved.quizScores?.[index] ? (lang === 'ar' ? 'مكتمل' : 'Completed') : (lang === 'ar' ? 'درس تعليمي' : 'Learning lesson')}</small></span><span class="lesson-status">${saved.quizScores?.[index] ? '✓' : '→'}</span></button>`).join(''); list.querySelectorAll('.lesson-nav').forEach(button => button.onclick = () => { current = Number(button.dataset.lessonIndex); renderShell(); }); renderLesson(items[current]); }
  function renderLesson(items) { const lesson = items[current]; const area = $('lesson-content'); if (!lesson || !area) return; const complete = saved.quizScores?.[current]; area.innerHTML = `<article class="lesson-content-card card"><div class="lesson-content-kicker">${lang === 'ar' ? `الدرس ${current + 1} من ${items.length}` : `Lesson ${current + 1} of ${items.length}`}</div><h2>${lesson.title}</h2><p class="lesson-body">${lesson.body}</p><div class="lesson-points"><h3>${lang === 'ar' ? 'نقاط أساسية' : 'Key points'}</h3><ul>${lesson.points.map(point => `<li>${point}</li>`).join('')}</ul></div><aside class="lesson-example"><strong>${lang === 'ar' ? 'تطبيق عملي' : 'Practical example'}</strong><p>${lesson.example}</p></aside>${complete ? `<div class="lesson-complete">✓ ${lang === 'ar' ? 'أكملت هذا الدرس والاختبار.' : 'You completed this lesson and quiz.'}</div>` : `<button class="btn primary open-lesson-quiz">${lang === 'ar' ? 'أنهيت الدرس — ابدأ الاختبار' : 'I finished the lesson — Start quiz'}</button>`}<div class="quiz-box" hidden></div></article>`; area.querySelector('.open-lesson-quiz')?.addEventListener('click', () => showQuiz(area.querySelector('.quiz-box'))); }
  function showQuiz(box) { const q = quiz[lang]; box.hidden = false; box.innerHTML = `<h3>${lang === 'ar' ? 'اختبار قصير' : 'Short quiz'}</h3><p>${q[0]}</p>${q[1].map((option, index) => `<label><input type="radio" name="lesson-quiz" value="${index}"> ${option}</label>`).join('')}<button class="btn primary check-quiz">${lang === 'ar' ? 'تصحيح الإجابة' : 'Check answer'}</button><span class="quiz-result"></span>`; box.querySelector('.check-quiz').onclick = async () => { const selected = box.querySelector('input:checked'); const output = box.querySelector('.quiz-result'); if (!selected) { output.textContent = lang === 'ar' ? 'اختر إجابة أولًا.' : 'Choose an answer first.'; return; } if (Number(selected.value) !== q[2]) { output.textContent = lang === 'ar' ? 'الإجابة غير صحيحة. راجع الدرس وحاول مرة أخرى.' : 'Incorrect. Review the lesson and try again.'; return; } const scores = { ...(saved.quizScores || {}), [current]: true }; const percent = Math.round(Object.values(scores).filter(Boolean).length / course.ar.lessons.length * 100); try { const result = await request(`/progress/${slug}`, { method: 'PUT', body: JSON.stringify({ percent, lastSection: current + 1, quizScores: scores, language: lang }) }); saved = result.progress; msg(lang === 'ar' ? 'تم حفظ إكمال الدرس في حسابك.' : 'Lesson completion saved to your account.'); if (current < course.ar.lessons.length - 1) current += 1; renderShell(); } catch (error) { output.textContent = error.message; } }; }
  async function init() {
    try {
      const result = await request('/progress');
      saved = result.progress?.find(item => item.courseSlug === slug) || saved;
      current = Math.min(Number(saved.lastSection || 0), course.ar.lessons.length - 1);
      renderShell();
    } catch (_) {
      msg(lang === 'ar' ? 'سجّل الدخول أولًا للوصول إلى الدورة.' : 'Please sign in first to access this course.');
      window.setTimeout(() => {
        const target = new URL('index.html', document.baseURI);
        target.searchParams.set('auth', 'required');
        target.searchParams.set('course', slug);
        window.location.replace(target.href);
      }, 450);
    }
  }
  document.querySelectorAll('[data-course-lang]').forEach(button => button.onclick = () => { lang = button.dataset.courseLang; localStorage.setItem('club-lang', lang); renderShell(); }); init();
})();
