(() => {
  'use strict';
  const API = '/api/learning';
  const data = {
    'cyber-basics': { ar: { name: 'أساسيات الأمن السيبراني', desc: 'مفاهيم التهديدات وحماية الحسابات والهندسة الاجتماعية.', level: 'سهل · مبتدئ', lessons: ['مقدمة الأمن السيبراني','إدارة الحسابات وكلمات المرور','الهندسة الاجتماعية','التصفح والبريد الآمن','المراجعة النهائية'] }, en: { name: 'Cybersecurity Basics', desc: 'Threats, account protection, and social engineering fundamentals.', level: 'Easy · Beginner', lessons: ['Cybersecurity introduction','Accounts and passwords','Social engineering','Safe browsing and email','Final review'] } },
    'network-defense': { ar: { name: 'الدفاع عن الشبكات', desc: 'مراقبة الشبكات وقراءة السجلات والاستجابة للحوادث.', level: 'متوسط الصعوبة', lessons: ['مبادئ الشبكات','الجدران النارية','قراءة السجلات','كشف التهديدات','الاستجابة للحوادث'] }, en: { name: 'Network Defense', desc: 'Network monitoring, log analysis, and incident response.', level: 'Intermediate', lessons: ['Network principles','Firewalls','Log analysis','Threat detection','Incident response'] } },
    'ethical-hacking': { ar: { name: 'الاختبار الاختراقي الأخلاقي', desc: 'الاختبار المصرح به واكتشاف الثغرات وكتابة التقارير.', level: 'صعب · متقدم', lessons: ['النطاق والتصريح','جمع المعلومات','فحص الثغرات','الاستغلال الآمن','كتابة التقرير'] }, en: { name: 'Ethical Hacking', desc: 'Authorized testing, vulnerability discovery, and reporting.', level: 'Hard · Advanced', lessons: ['Scope and authorization','Reconnaissance','Vulnerability scanning','Safe exploitation','Report writing'] } }
  };
  const quiz = { ar: ['ما الهدف الأساسي من الأمن السيبراني؟',['حماية البيانات والأنظمة','زيادة سرعة الإنترنت','إلغاء كلمات المرور']], en: ['What is the primary goal of cybersecurity?',['Protecting data and systems','Increasing internet speed','Removing passwords']] };
  const slug = new URLSearchParams(location.search).get('course') || 'cyber-basics'; let lang = localStorage.getItem('club-lang') === 'en' ? 'en' : 'ar'; let saved = { percent: 0, lastSection: 0, quizScores: {} }; const course = data[slug] || data['cyber-basics'];
  const $ = (id) => document.getElementById(id); const msg = (t) => { $('course-message').textContent = t; };
  async function request(path, options = {}) { const r = await fetch(`${API}${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json' }, ...options }); const d = await r.json().catch(() => ({})); if (!r.ok) throw Error(d.error || 'تعذر الاتصال بالخادم'); return d; }
  function render() { const c = course[lang]; document.documentElement.lang = lang; document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'; $('course-title').textContent = c.name; $('course-description').textContent = c.desc; $('course-level').textContent = c.level; $('course-progress').textContent = `${saved.percent || 0}%`; $('course-progress-bar').style.width = `${saved.percent || 0}%`; document.querySelectorAll('[data-course-lang]').forEach(b => b.classList.toggle('active', b.dataset.courseLang === lang)); $('lessons').innerHTML = c.lessons.map((title, i) => `<article class="lesson-card card"><div><span class="lesson-number">${i + 1}</span><h2>${title}</h2><p>${saved.quizScores?.[i] ? (lang === 'ar' ? 'تم اجتياز الاختبار' : 'Quiz passed') : (lang === 'ar' ? 'درس واختبار قصير' : 'Lesson and short quiz')}</p></div><button class="btn primary lesson-quiz" data-index="${i}">${saved.quizScores?.[i] ? (lang === 'ar' ? 'إعادة الاختبار' : 'Retake quiz') : (lang === 'ar' ? 'ابدأ الاختبار' : 'Start quiz')}</button><div class="quiz-box" hidden></div></article>`).join(''); document.querySelectorAll('.lesson-quiz').forEach(b => b.onclick = () => showQuiz(b.closest('.lesson-card'), Number(b.dataset.index))); }
  function showQuiz(card, index) { const box = card.querySelector('.quiz-box'); const q = quiz[lang]; box.hidden = false; box.innerHTML = `<p>${q[0]}</p>${q[1].map((o,i) => `<label><input type="radio" name="q-${index}" value="${i}"> ${o}</label>`).join('')}<button class="btn primary check-quiz">${lang === 'ar' ? 'تصحيح الإجابة' : 'Check answer'}</button><span class="quiz-result"></span>`; box.querySelector('.check-quiz').onclick = async () => { const selected = box.querySelector('input:checked'); const out = box.querySelector('.quiz-result'); if (!selected) { out.textContent = lang === 'ar' ? 'اختر إجابة أولًا.' : 'Choose an answer first.'; return; } if (Number(selected.value) !== 0) { out.textContent = lang === 'ar' ? 'إجابة غير صحيحة، حاول مرة أخرى.' : 'Incorrect, try again.'; return; } const scores = { ...(saved.quizScores || {}), [index]: true }; const percent = Math.round(Object.values(scores).filter(Boolean).length / course.ar.lessons.length * 100); try { const d = await request(`/progress/${slug}`, { method: 'PUT', body: JSON.stringify({ percent, lastSection: index + 1, quizScores: scores, language: lang }) }); saved = d.progress; render(); msg(lang === 'ar' ? 'تم حفظ تقدمك على حسابك.' : 'Your progress was saved to your account.'); } catch (e) { out.textContent = e.message; } }; }
  async function init() { try { const d = await request('/progress'); saved = d.progress?.find(x => x.courseSlug === slug) || saved; } catch (_) { msg(lang === 'ar' ? 'سجّل الدخول للوصول إلى الدورة.' : 'Please sign in to access this course.'); } render(); }
  document.querySelectorAll('[data-course-lang]').forEach(b => b.onclick = () => { lang = b.dataset.courseLang; localStorage.setItem('club-lang', lang); render(); }); init();
})();
